export const chefTable = [
    {
      email: "ramsay@gmail.com",
      password: "password123",
      aboutMe: "I am a professional chef with over 10 years of experience in the industry.",
      cuisineType: "1",
      postCode: "1000",
      chefPhoto: "https://www.seekpng.com/png/detail/118-1180558_gordon-ramsay-hells-kitchen-season-1-10-dvd.png",
      secondName: "Gordan",
      firstName: "ramsay",
      address: "123 Main St, Anytown ",
      phone: "555-555-1212"
    },
    {
      email: "ramdoss@gmail.com",
      password: "password456",
      aboutMe: "I have a passion for cooking and love to experiment with different ingredients and flavors.",
      cuisineType: "2",
      postCode: "1020",
      chefPhoto: "https://images.pexels.com/photos/8136890/pexels-photo-8136890.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      secondName: "Ram",
      firstName: "doss",
      address: "456 Main St, Anytown ",
      phone: "555-555-1213"
    },
    {
      email: "jimsmith@gmail.com",
      password: "password789",
      aboutMe: "I specialize in creating unique and delicious dishes for special occasions and events.",
      cuisineType: "3",
      postCode: "1200",
      chefPhoto: "https://images.pexels.com/photos/7698235/pexels-photo-7698235.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      secondName: "Smith",
      firstName: "Jim",
      address: "789 Main St, Anytown ",
      phone: "555-555-1214"
    },
    {
      email: "jillsmith@gmail.com",
      password: "password246",
      aboutMe: "I have a talent for creating flavorful and healthy dishes that please both the taste buds and the waistline.",
      cuisineType: "4",
      postCode: "1201",
      chefPhoto: "https://images.pexels.com/photos/8879388/pexels-photo-8879388.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      secondName: "Smith",
      firstName: "Jill",
      address: "246 Main St, Anytown USA",
      phone: "555-555-1215"
    },
    {
      email: "jackjohnson@gmail.com",
      password: "password369",
      aboutMe: "I am an expert in creating gourmet meals using only the freshest and highest quality ingredients.",
      cuisineType: "5",
      postCode: "1200",
      chefPhoto: "https://images.pexels.com/photos/6050329/pexels-photo-6050329.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      secondName: "Johnson",
      firstName: "Jack",
      address: "369 Main St, Anytown ",
      phone: "555-555-1216"
    },
    {
        email: "JohnSmith@gmail.com",
        password: "password1",
        aboutMe: "I am a food enthusiast and love trying out new cuisines.",
        cuisineType: "6",
        postCode: "1001",
        chefPhoto: "https://images.pexels.com/photos/7447293/pexels-photo-7447293.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        secondName: "Smith",
        firstName: "John",
        address: "123 Main St",
        phone: "555-555-5555"
      },
      {
        email: "JaneJohnson@gmail.com",
        password: "password2",
        aboutMe: "I am a professional chef with over 10 years of experience in cooking.",
        cuisineType: "7",
        postCode: "1100",
        chefPhoto: "https://images.pexels.com/photos/3771812/pexels-photo-3771812.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        secondName: "Johnson",
        firstName: "Jane",
        address: "456 Main St",
        phone: "555-555-5556"
      },
      {
        email: "Bob@gmail.com",
        password: "password3",
        aboutMe: "I love experimenting with different ingredients and creating unique dishes.",
        cuisineType: "8",
        postCode: "1200",
        chefPhoto: "https://images.pexels.com/photos/6248810/pexels-photo-6248810.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        secondName: "Williams",
        firstName: "Bob",
        address: "789 Main St",
        phone: "555-555-5557"
      },
      {
        email: "Emma@gmail.com",
        password: "password4",
        aboutMe: "I have a passion for baking and enjoy creating sweet treats.",
        cuisineType: "1",
        postCode: "1001",
        chefPhoto: "https://images.pexels.com/photos/11792243/pexels-photo-11792243.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        secondName: "Brown",
        firstName: "Emma",
        address: "321 Main St",
        phone: "555-555-5558"
      },
      {
        email: "Madhavan@gmail.com",
        password: "password5",
        aboutMe: "I love cooking traditional dishes and sharing them with others.",
        cuisineType: "2",
        postCode: "1100",
        chefPhoto: "https://www.filmibeat.com/img/2021/04/madhavan1-1618553848.jpg",
        secondName: "Maddy",
        firstName: "Madhavan",
        address: "654 Main St",
        phone: "555-555-5559"
      },
      {
        email: "Sophie@gmail.com",
        password: "password6",
        aboutMe: "I have a background in fine dining and enjoy creating upscale dishes.",
        cuisineType: "3",
        postCode: "1000",
        chefPhoto: "https://images.pexels.com/photos/6957845/pexels-photo-6957845.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        secondName: "Miller",
        firstName: "Sophie",
        address: "987 Main St",
        phone: "555-555-5560"
      },
      //

      {
        email: "tiffanyJane@gmail.com",
        password: "password123",
        aboutMe: "I am a professional chef with over 10 years of experience in the industry.",
        cuisineType: "1",
        postCode: "1000",
        chefPhoto: "https://images.pexels.com/photos/9399544/pexels-photo-9399544.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        secondName: "tiffany",
        firstName: "Jane",
        address: "123 Main St, Anytown ",
        phone: "555-555-1212"
      },
      {
        email: "lakshmi@gmail.com",
        password: "password456",
        aboutMe: "I have a passion for cooking and love to experiment with different ingredients and flavors.",
        cuisineType: "2",
        postCode: "1020",
        chefPhoto: "https://eng.cinereporters.com/wp-content/uploads/2022/10/keerthi3-3.jpg",
        secondName: "kala",
        firstName: "lakshmi",
        address: "456 Main St, Anytown ",
        phone: "555-555-1213"
      },
      {
        email: "Tomsmith@gmail.com",
        password: "password789",
        aboutMe: "I specialize in creating unique and delicious dishes for special occasions and events.",
        cuisineType: "3",
        postCode: "1200",
        chefPhoto: "https://images.pexels.com/photos/5593344/pexels-photo-5593344.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        secondName: "Smith",
        firstName: "Tom",
        address: "789 Main St, Anytown ",
        phone: "555-555-1214"
      },
      {
        email: "jacksmith@gmail.com",
        password: "password246",
        aboutMe: "I have a talent for creating flavorful and healthy dishes that please both the taste buds and the waistline.",
        cuisineType: "4",
        postCode: "1201",
        chefPhoto: "https://images.pexels.com/photos/3873973/pexels-photo-3873973.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        secondName: "Smith",
        firstName: "Jack",
        address: "246 Main St, Anytown USA",
        phone: "555-555-1215"
      },
      {
        email: "jackAntony@gmail.com",
        password: "password369",
        aboutMe: "I am an expert in creating gourmet meals using only the freshest and highest quality ingredients.",
        cuisineType: "5",
        postCode: "1200",
        chefPhoto: "https://images.pexels.com/photos/8805796/pexels-photo-8805796.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        secondName: "Antony",
        firstName: "Jack",
        address: "369 Main St, Anytown ",
        phone: "555-555-1216"
      },
      {
          email: "tony@gmail.com",
          password: "password1",
          aboutMe: "I am a food enthusiast and love trying out new cuisines.",
          cuisineType: "6",
          postCode: "1001",
          chefPhoto: "https://images.pexels.com/photos/7447293/pexels-photo-7447293.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          secondName: "Smith",
          firstName: "Tony",
          address: "123 Main St",
          phone: "555-555-5555"
        },
        {
          email: "Jane@gmail.com",
          password: "password2",
          aboutMe: "I am a professional chef with over 10 years of experience in cooking.",
          cuisineType: "7",
          postCode: "1100",
          chefPhoto: "https://images.pexels.com/photos/8902109/pexels-photo-8902109.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          secondName: "Johnson",
          firstName: "Jane",
          address: "456 Main St",
          phone: "555-555-5556"
        },
        {
          email: "Bob@gmail.com",
          password: "password3",
          aboutMe: "I love experimenting with different ingredients and creating unique dishes.",
          cuisineType: "8",
          postCode: "1200",
          chefPhoto: "https://images.pexels.com/photos/6019592/pexels-photo-6019592.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          secondName: "Williams",
          firstName: "Bob",
          address: "789 Main St",
          phone: "555-555-5557"
        },
        {
          email: "Emma@gmail.com",
          password: "password4",
          aboutMe: "I have a passion for baking and enjoy creating sweet treats.",
          cuisineType: "1",
          postCode: "1001",
          chefPhoto: "https://images.pexels.com/photos/7965977/pexels-photo-7965977.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          secondName: "Brown",
          firstName: "Emma",
          address: "321 Main St",
          phone: "555-555-5558"
        },
        {
          email: "David@gmail.com",
          password: "password5",
          aboutMe: "I love cooking traditional dishes and sharing them with others.",
          cuisineType: "2",
          postCode: "1100",
          chefPhoto: "https://images.pexels.com/photos/7129381/pexels-photo-7129381.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          secondName: "Raman",
          firstName: "David",
          address: "654 Main St",
          phone: "555-555-5559"
        },
        {
          email: "Sophie@gmail.com",
          password: "password6",
          aboutMe: "I have a background in fine dining and enjoy creating upscale dishes.",
          cuisineType: "3",
          postCode: "1000",
          chefPhoto: "https://images.pexels.com/photos/4057693/pexels-photo-4057693.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          secondName: "Miller",
          firstName: "Sophie",
          address: "987 Main St",
          phone: "555-555-5560"
        },

]